name: hello-world
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DIALECT: "${{ secrets.DB_DIALECT }}"
      DB_HOST: "${{ secrets.DB_HOST }}"
      DB_PORT: "${{ secrets.DB_PORT }}"
      DB_USERNAME: "${{ secrets.DB_USERNAME }}"
      DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
      DB_NAME_CREATED: "${{ secrets.DB_NAME_CREATED }}"
      DB_NAME_DEFAULT: "${{ secrets.DB_NAME_DEFAULT }}"
      DB_LOGGING: "${{ secrets.DB_LOGGING }}"
      CSV_LOCATION: "${{ secrets.CSV_LOCATION }}"
      SERVER_PORT: "${{ secrets.SERVER_PORT }}"

    steps:
      - name: Checkout Code
        run: |
          if [ "$DB_USERNAME" == "postgre"]
          then 
            echo "true asdasd"
          fi

